### ISSUE TITLE
Fix "similar-code" issue in project/main/business/get_business_helper.py

### ISSUE THREAD

**Issue by SabCampos** [qAIRa/qAIRaMapAPI-OpenSource#107]
The file [get_business_helper.py](https://github.com/qAIRa/qAIRaMapAPI-OpenSource/blob/master/project/main/business/get_business_helper.py) contains functions that query our DB tables dedicated to everything that is not related to air quality measurements. 

Similar blocks of code found in 2 locations. Consider refactoring.

Block 1, lines 155...159:

              def getAllMobileQhawaxID():
                  """ Gets all mobile qHAWAXs - No parameters required """
                  base_string = "MOBILE_EXT"
                  search = "%{}%".format(base_string)
                  qhawax_list =  session.query(Qhawax.id).filter(Qhawax.qhawax_type.like(search)). \

Block 2, lines 137...141:

            def getAllStaticQhawaxID():
                """ Get all qHAWAXs STATIC (int or ext) ID - No parameters required """
                base_string = "STATIC"
                search = "%{}%".format(base_string)
                qhawax_list =  session.query(Qhawax.id).filter(Qhawax.qhawax_type.like(search)). \

**Comment by AlisonLiii** [comment]
Hi! I am from vGHC. Can you assign this to me? Thanks!
