### ISSUE TITLE
Add pre-commit to avoid common styling errors

### ISSUE THREAD

**Issue by bhattbhuwan13** [qAIRa/qAIRaMapAPI-OpenSource#108]
I see that the code has significant number of issues related to python styling convention violation. As such, it would be a great idea to add [pre-commit](https://pre-commit.com) so that new developers can readily use it and avoid violating python code convention.

**Comment by bhattbhuwan13** [comment]
@GersonMontesinos @SabCampos , Let me know your thoughts. I have a pre-commit config file ready and I can push them here if you guys permit.

**Comment by GersonMontesinos** [comment]
> @GersonMontesinos @SabCampos , Let me know your thoughts. I have a pre-commit config file ready and I can push them here if you guys permit.

Hello @bhattbhuwan13 ! To be completely honest, we had no clue that such library existed. By the description of it, our project must have that to avoid pushing errors that the library may find.
